on: 
  pull_request: 
    branches: 
      - main

jobs:
  deploy: 
    name: "Deploy check"
    runs-on: ubuntu-latest
    steps: 
      # Check out project 
      - name: Checkout
        uses: actions/checkout@v3
      
      # Build using the peon script on production
      - name: Build 
        run: /bin/bash ./peon.sh build production
      
      
      
      

